# Generated by Django 6.0.5 on 2026-05-14 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entree',
            old_name='date',
            new_name='date_creation',
        ),
        migrations.RenameField(
            model_name='entree',
            old_name='Titre',
            new_name='titre',
        ),
    ]
