# Generated by Django 6.0.5 on 2026-05-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0002_rename_date_entree_date_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entree',
            name='etat',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('resolu', 'Résolu'), ('bloque', 'Bloqué')], default='en_cours', max_length=20),
        ),
    ]
