# Generated by Django 6.0.5 on 2026-05-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0003_entree_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entree',
            name='image_de_preuve',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
